/**
 * Type of actions the pets reducer can perform
 */

const PetsTypes = {
  // pets
  GET_PETS_START: "GET_PETS_START",
  GET_PETS_SUCCESS: "GET_PETS_SUCCESS",
  GET_PETS_FAILURE: "GET_PETS_FAILURE",

  // types
  GET_TYPES_START: "GET_TYPES_START",
  GET_TYPES_SUCCESS: "GET_TYPES_SUCCESS",
  GET_TYPES_FAILURE: "GET_TYPES_FAILURE",

  // breeds
  GET_BREEDS_START: "GET_BREEDS_START",
  GET_BREEDS_SUCCESS: "GET_BREEDS_SUCCESS",
  GET_BREEDS_FAILURE: "GET_BREEDS_FAILURE",

  // details
  GET_DETAILS_START: "GET_DETAILS_START",
  GET_DETAILS_SUCCESS: "GET_DETAILS_SUCCESS",
  GET_DETAILS_FAILURE: "GET_DETAILS_FAILURE",
};

export default PetsTypes;
